#! /bin/bash 

target="http://www.spamhaus.org/drop/drop.txt" 

filename=$(basename ${target}) 
firewall_ipset="spamhaus-${filename%.*}"           # ipset will be filename minus ext 
data_dir="/var/tmp/${firewall_ipset}"   # data directory will be same 
data_file="${data_dir}/${filename}" 

# if data directory does not exist, create it 
mkdir -pm 0750 ${data_dir} 



# sync if file at least one hour old :=???
sync_after=3600

last=$(date -r ${data_file} '+%s')
curr=$(date '+%s')

diffr=$[$curr - $last]

if [ $diffr -gt $sync_after ]; then
    # fetch file only if newer than the version we already have 
    wget -qNP ${data_dir} ${target} 
    if [ "$?" -ne "0" ]; then 
        logger -p cron.err "IPSet: ${firewall_ipset} wget failed." 
        exit 1 
    fi 

#else
#	exit 0
fi



ipcount=$(wc -l  $data_file | grep -Po "[0-9]* ")
ipcount=$[$ipcount + 10]

ipset_params="hash:net maxelem ${ipcount}"

temp_ipset="${firewall_ipset}_temp" 
human_timestamp=$(date +%m/%d' '%R)
echo "create ${temp_ipset} ${ipset_params}" > "${data_file}.sv"
sed -rn "s/(^([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,3}).*$/add ${temp_ipset} \1/p" ${data_file} >> "${data_file}.sv"

ipset restore < "${data_file}.sv"

ipset create -exist ${firewall_ipset} ${ipset_params}

# swap the temp ipset for the live one 
ipset swap ${temp_ipset} ${firewall_ipset} 
ipset destroy ${temp_ipset} 

# log the file modification time for use in minimizing lag in cron schedule 
logger -p cron.notice "IPSet: ${firewall_ipset} updated (as of: ${human_timestamp})." 

rm "${data_file}.sv"

